import "server-only";
import { mapWithConcurrency } from "./image-check";

/* Live-site health: compares Supabase (source of truth) against what
 * actiongames.io actually serves. The DB-only scan in /api/health/scan can't
 * see any of this — a game row can be perfectly valid and still 404 in
 * production, or stay out of the sitemap for weeks, because the live site
 * serves cached output.
 *
 * Two failure classes this catches, both of which show up in Search Console
 * as "Not found (404)" / "Page with redirect":
 *   • dead in sitemap  — game deleted from the DB, sitemap still lists it →
 *                        Google crawls the URL and gets a hard 404.
 *   • missing from sitemap — game added to the DB, sitemap still cached →
 *                        Google never discovers it.
 */

export const SITE_URL = (process.env.SITE_URL ?? "https://actiongames.io").replace(/\/$/, "");

const TIMEOUT_MS = 10_000;
/* Enough of a sample to notice a site-wide cache/deploy problem without
 * probing the whole catalog on every run. */
const CANARY_SAMPLE = 25;

export type Severity = "error" | "warn";

export interface LiveIssue {
  label: string;
  severity: Severity;
  detail?: string;
}

export interface ProbeResult {
  slug: string;
  url: string;
  status: number; // 0 = request failed outright
  ok: boolean;
  reason: "in-db" | "dead-in-sitemap";
}

export interface LiveReport {
  siteUrl: string;
  checkedAt: string;
  deep: boolean;
  dbCount: number;
  live: {
    reachable: boolean;
    gameCount?: number;
    catalogSource?: string;
    error?: string;
  };
  sitemap: {
    reachable: boolean;
    totalUrls: number;
    gameUrls: number;
    newestLastmod: string | null;
    ageDays: number | null;
    error?: string;
  };
  /* In the DB but absent from the live sitemap → Google can't discover them. */
  missingFromSitemap: string[];
  /* In the live sitemap but gone from the DB → guaranteed crawl 404. */
  deadInSitemap: string[];
  /* Live URLs that did not return 200. */
  broken: ProbeResult[];
  probedCount: number;
  /* True when the site started refusing probes — the probe results are then a
   * partial sample, not a clean bill of health. */
  blocked: boolean;
  issues: LiveIssue[];
}

async function fetchText(url: string): Promise<string> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    /* cache: "no-store" — we want what the CDN serves right now, not a
     * response Next cached inside this admin app. */
    const res = await fetch(url, { signal: ctrl.signal, cache: "no-store" });
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    return await res.text();
  } finally {
    clearTimeout(timer);
  }
}

/* Probe one public game URL. HEAD is enough — we only care about the status
 * code, and a 404 page still returns a body we'd otherwise download. */
async function probeOnce(url: string): Promise<number> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: "HEAD",
      signal: ctrl.signal,
      cache: "no-store",
      redirect: "follow",
    });
    return res.status;
  } catch {
    return 0;
  } finally {
    clearTimeout(timer);
  }
}

/* A deep check fires ~900 requests at one host, so some will time out purely
 * from the load. Retrying once keeps a transient failure from being reported
 * as a broken page — a real 404 answers immediately and never gets here. */
async function probeUrl(url: string): Promise<number> {
  const status = await probeOnce(url);
  if (status !== 0) return status;
  await new Promise((r) => setTimeout(r, 500));
  return probeOnce(url);
}

/* Vercel answers a burst of requests from one IP with a "Security Checkpoint"
 * (403) or a rate limit (429). Every probe after that point looks broken, which
 * would turn this report into a wall of false 404s — the exact false alarm the
 * tool exists to prevent. Treat it as "stop and say so" instead. */
function isBlocked(status: number): boolean {
  return status === 403 || status === 429;
}

interface SitemapParse {
  totalUrls: number;
  gameSlugs: Set<string>;
  newestLastmod: string | null;
}

/* The sitemap is generated by us and always well-formed, so a regex beats
 * pulling in an XML parser for two fields. */
export function parseSitemap(xml: string, base: string): SitemapParse {
  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]!.trim());
  const prefix = `${base}/games/`;
  const gameSlugs = new Set(
    locs.filter((u) => u.startsWith(prefix)).map((u) => u.slice(prefix.length)),
  );

  const mods = [...xml.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)]
    .map((m) => m[1]!.trim())
    .filter((d) => !Number.isNaN(Date.parse(d)))
    .sort();

  return {
    totalUrls: locs.length,
    gameSlugs,
    newestLastmod: mods.length ? mods[mods.length - 1]! : null,
  };
}

async function readLiveHealth(): Promise<LiveReport["live"]> {
  try {
    const json = JSON.parse(await fetchText(`${SITE_URL}/api/health`)) as {
      gameCount?: number;
      catalogSource?: string;
    };
    return {
      reachable: true,
      gameCount: json.gameCount,
      catalogSource: json.catalogSource,
    };
  } catch (err) {
    return { reachable: false, error: (err as Error).message };
  }
}

/* `deep` probes every game in the DB (slow, ~1 request per game). The default
 * probes only the URLs we already suspect, plus a small random canary sample
 * that would catch a site-wide outage or a bad deploy. */
export async function runLiveCheck(
  dbSlugs: string[],
  opts: { deep?: boolean } = {},
): Promise<LiveReport> {
  const deep = opts.deep ?? false;
  const checkedAt = new Date().toISOString();
  const dbSet = new Set(dbSlugs);

  const [live, sitemapResult] = await Promise.all([
    readLiveHealth(),
    fetchText(`${SITE_URL}/sitemap.xml`)
      .then((xml) => ({ ok: true as const, parsed: parseSitemap(xml, SITE_URL) }))
      .catch((err: Error) => ({ ok: false as const, error: err.message })),
  ]);

  const parsed = sitemapResult.ok ? sitemapResult.parsed : null;

  const missingFromSitemap = parsed
    ? dbSlugs.filter((s) => !parsed.gameSlugs.has(s))
    : [];
  const deadInSitemap = parsed
    ? [...parsed.gameSlugs].filter((s) => !dbSet.has(s))
    : [];

  /* Dead sitemap entries are the direct 404 source — always probe all of them.
   * Everything else is either the full catalog (deep) or a canary sample. */
  const canaries = deep
    ? dbSlugs
    : [...dbSlugs].sort(() => Math.random() - 0.5).slice(0, CANARY_SAMPLE);

  const targets: { slug: string; reason: ProbeResult["reason"] }[] = [
    ...deadInSitemap.map((slug) => ({ slug, reason: "dead-in-sitemap" as const })),
    ...canaries.map((slug) => ({ slug, reason: "in-db" as const })),
  ];

  /* Far lower than the image scan's 24: those requests fan out across many CDNs,
   * these all hit one origin. Deep mode is ~900 requests, and going fast enough
   * to look like an attack gets the whole scan blocked (see `blocked` below). */
  let blocked = false;
  const probes = await mapWithConcurrency(targets, 5, async (t) => {
    const url = `${SITE_URL}/games/${t.slug}`;
    if (blocked) return { slug: t.slug, url, status: -1, ok: true, reason: t.reason };
    const status = await probeUrl(url);
    if (isBlocked(status)) blocked = true;
    return { slug: t.slug, url, status, ok: status === 200, reason: t.reason };
  });

  /* status -1 = skipped after a block; never report those as broken. */
  const broken = probes.filter((p) => !p.ok && p.status !== -1);

  const ageDays =
    parsed?.newestLastmod != null
      ? Math.floor((Date.now() - Date.parse(parsed.newestLastmod)) / 86_400_000)
      : null;

  const issues: LiveIssue[] = [];

  if (!live.reachable)
    issues.push({ label: "live site unreachable", severity: "error", detail: live.error });
  else if (live.catalogSource && live.catalogSource !== "supabase")
    issues.push({
      label: `live site is not reading Supabase (${live.catalogSource})`,
      severity: "error",
    });
  else if (live.gameCount != null && live.gameCount !== dbSlugs.length)
    issues.push({
      label: "live game count is behind the DB",
      severity: "warn",
      detail: `live ${live.gameCount} vs DB ${dbSlugs.length} — the site cache has not caught up yet`,
    });

  if (!sitemapResult.ok)
    issues.push({
      label: "sitemap unreachable",
      severity: "error",
      detail: "error" in sitemapResult ? sitemapResult.error : undefined,
    });

  if (deadInSitemap.length)
    issues.push({
      label: `${deadInSitemap.length} deleted games still in the sitemap`,
      severity: "error",
      detail: "Google will crawl these and get a 404. Revalidate to drop them.",
    });

  if (missingFromSitemap.length)
    issues.push({
      label: `${missingFromSitemap.length} games missing from the sitemap`,
      severity: "error",
      detail: "Google cannot discover these. Revalidate to publish them.",
    });

  if (blocked)
    issues.push({
      label: "the site rate-limited this check — probe results are incomplete",
      severity: "warn",
      detail:
        "Vercel returned a security checkpoint / 429, so probing stopped early. The sitemap comparison above is still accurate; wait a few minutes before probing again.",
    });

  const brokenInDb = broken.filter((b) => b.reason === "in-db");
  if (brokenInDb.length)
    issues.push({
      label: `${brokenInDb.length}/${canaries.length} live game pages not returning 200`,
      severity: "error",
      detail: deep
        ? "These games exist in the DB but 404 on the live site."
        : "Sampled check — run a deep check to probe every game.",
    });

  /* A sitemap whose newest entry is old means the XML itself is a stale cache
   * entry, not that the catalog stopped growing. */
  if (ageDays != null && ageDays > 7 && missingFromSitemap.length > 0)
    issues.push({
      label: `sitemap looks frozen (newest entry ${ageDays} days old)`,
      severity: "error",
      detail: "Revalidate the live site; if it stays frozen, redeploy the web app.",
    });

  return {
    siteUrl: SITE_URL,
    checkedAt,
    deep,
    dbCount: dbSlugs.length,
    live,
    sitemap: {
      reachable: sitemapResult.ok,
      totalUrls: parsed?.totalUrls ?? 0,
      gameUrls: parsed?.gameSlugs.size ?? 0,
      newestLastmod: parsed?.newestLastmod ?? null,
      ageDays,
      error: sitemapResult.ok ? undefined : sitemapResult.error,
    },
    missingFromSitemap,
    deadInSitemap,
    broken,
    probedCount: probes.filter((p) => p.status !== -1).length,
    blocked,
    issues: issues.sort((a, b) => (a.severity === b.severity ? 0 : a.severity === "error" ? -1 : 1)),
  };
}
